// <auto-generated />
using System;
using ClinicAppointmentProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAppointmentProject.Migrations
{
    [DbContext(typeof(ClinicAppointmentDatabaseContext))]
    partial class ClinicAppointmentDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicAppointmentProject.Models.Appointment", b =>
                {
                    b.Property<int>("appointment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appointment_id"));

                    b.Property<DateOnly>("created_at")
                        .HasColumnType("date");

                    b.Property<int>("doctor_id")
                        .HasColumnType("int");

                    b.Property<int?>("pateint_id")
                        .HasColumnType("int");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<int>("slot_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("appointment_id");

                    b.HasIndex("doctor_id");

                    b.HasIndex("pateint_id");

                    b.HasIndex("slot_id");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.AvailabilitySlots", b =>
                {
                    b.Property<int>("slot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("slot_id"));

                    b.Property<int>("doctor_id")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("end_time")
                        .HasColumnType("time");

                    b.Property<DateOnly>("slot_date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("slot_time")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("time");

                    b.HasKey("slot_id");

                    b.HasIndex("doctor_id");

                    b.ToTable("AvailabilitySlots");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.Doctor", b =>
                {
                    b.Property<int>("doctor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("doctor_id"));

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("specialty_id")
                        .HasColumnType("int");

                    b.HasKey("doctor_id");

                    b.HasIndex("specialty_id");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.Patient", b =>
                {
                    b.Property<int>("patient_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patient_id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("dob")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("patient_id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.Specialty", b =>
                {
                    b.Property<int>("specialty_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("specialty_id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("specialty_id");

                    b.ToTable("Specialty");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.StatusHistory", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("status_id"));

                    b.Property<int>("appointment_id")
                        .HasColumnType("int");

                    b.Property<string>("changed_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("changed_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("previous_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updated_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("status_id");

                    b.HasIndex("appointment_id");

                    b.ToTable("StatusHistory");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.StatusLookup", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("status_id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("status_id");

                    b.ToTable("StatusLookup");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.Appointment", b =>
                {
                    b.HasOne("ClinicAppointmentProject.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAppointmentProject.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("pateint_id");

                    b.HasOne("ClinicAppointmentProject.Models.AvailabilitySlots", "AvailabilitySlots")
                        .WithMany("Appointments")
                        .HasForeignKey("slot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.AvailabilitySlots", b =>
                {
                    b.HasOne("ClinicAppointmentProject.Models.Doctor", "Doctor")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });


            modelBuilder.Entity("ClinicAppointmentProject.Models.Doctor", b =>
                {
                    b.HasOne("ClinicAppointmentProject.Models.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("specialty_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.StatusHistory", b =>
                {
                    b.HasOne("ClinicAppointmentProject.Models.Appointment", "Appointment")
                        .WithMany("StatusHistories")
                        .HasForeignKey("appointment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.Appointment", b =>
                {
                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.AvailabilitySlots", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailabilitySlots");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicAppointmentProject.Models.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
